
export enum ACTIONS {
  SHOW_ALERT = 'ALERTS/SHOW_ALERT',
  HIDE_ALERT = 'ALERTS/HIDE_ALERT',
  SHOW_LOADER = 'ALERTS/SHOW_LOADER',
  HIDE_LOADER = 'ALERTS/HIDE_LOADER',
  USER_DATA = 'AUTH/USER_DATA',
  UPDATE_CART = 'CART/UPDATE_CART',
  MODAL_WINDOW_DELETE_PRODUCT = 'MODAL/MODAL_WINDOW_DELETE_PRODUCT',
  MODAL_WINDOW_DELETE_PRODUCTS = 'MODAL/MODAL_WINDOW_DELETE_PRODUCTS',
  MODAL_WINDOW_DELETE_CATEGORY = 'MODAL/MODAL_WINDOW_DELETE_CATEGORY',
  MODAL_WINDOW_DELETE_ACCOUNT = 'MODAL/MODAL_WINDOW_DELETE_ACCOUNT',
  MODAL_WINDOW_DELETE_OR_ADD_AVATAR = 'MODAL/MODAL_WINDOW_DELETE_OR_ADD_AVATAR'
}